export const mockData = [
  {
    id: 1,
    first_name: "Georg",
    last_name: "Kropp",
    age: 61,
    visits: 76247,
    progress: 14,
    status: "complicated",
  },
  {
    id: 2,
    first_name: "Siobhan",
    last_name: "Ferentz",
    age: 59,
    visits: 57520,
    progress: 95,
    status: "complicated",
  },
  {
    id: 3,
    first_name: "Reuven",
    last_name: "Boik",
    age: 68,
    visits: 22708,
    progress: 9,
    status: "single",
  },
  {
    id: 4,
    first_name: "Jamie",
    last_name: "Milbourne",
    age: 44,
    visits: 28171,
    progress: 28,
    status: "relationship",
  },
  {
    id: 5,
    first_name: "Maurine",
    last_name: "Canny",
    age: 63,
    visits: 3882,
    progress: 89,
    status: "single",
  },
  {
    id: 6,
    first_name: "Joycelin",
    last_name: "Rean",
    age: 62,
    visits: 83617,
    progress: 79,
    status: "relationship",
  },
  {
    id: 7,
    first_name: "Broddie",
    last_name: "Schutt",
    age: 53,
    visits: 84301,
    progress: 99,
    status: "complicated",
  },
  {
    id: 8,
    first_name: "Othella",
    last_name: "Engelbrecht",
    age: 58,
    visits: 98221,
    progress: 56,
    status: "complicated",
  },
  {
    id: 9,
    first_name: "Ursola",
    last_name: "Fidge",
    age: 31,
    visits: 96366,
    progress: 38,
    status: "relationship",
  },
  {
    id: 10,
    first_name: "Pattie",
    last_name: "Tamblyn",
    age: 35,
    visits: 63483,
    progress: 31,
    status: "relationship",
  },
  {
    id: 11,
    first_name: "Corina",
    last_name: "Thewles",
    age: 31,
    visits: 73453,
    progress: 2,
    status: "relationship",
  },
  {
    id: 12,
    first_name: "Quinn",
    last_name: "Cowl",
    age: 51,
    visits: 90893,
    progress: 56,
    status: "complicated",
  },
  {
    id: 13,
    first_name: "Ferd",
    last_name: "Trudgion",
    age: 33,
    visits: 46833,
    progress: 25,
    status: "single",
  },
  {
    id: 14,
    first_name: "Skippy",
    last_name: "Cracie",
    age: 28,
    visits: 19442,
    progress: 79,
    status: "relationship",
  },
  {
    id: 15,
    first_name: "Hamish",
    last_name: "Warby",
    age: 70,
    visits: 21318,
    progress: 11,
    status: "single",
  },
  {
    id: 16,
    first_name: "Larissa",
    last_name: "Gove",
    age: 64,
    visits: 96265,
    progress: 43,
    status: "complicated",
  },
  {
    id: 17,
    first_name: "Maddi",
    last_name: "Harsum",
    age: 35,
    visits: 31949,
    progress: 6,
    status: "single",
  },
  {
    id: 18,
    first_name: "Spencer",
    last_name: "Blythin",
    age: 49,
    visits: 14477,
    progress: 65,
    status: "single",
  },
  {
    id: 19,
    first_name: "Brice",
    last_name: "Huthart",
    age: 49,
    visits: 30316,
    progress: 63,
    status: "complicated",
  },
  {
    id: 20,
    first_name: "Almira",
    last_name: "Baughan",
    age: 52,
    visits: 46554,
    progress: 79,
    status: "complicated",
  },
  {
    id: 21,
    first_name: "Tamar",
    last_name: "Vell",
    age: 68,
    visits: 77529,
    progress: 45,
    status: "single",
  },
  {
    id: 22,
    first_name: "Hendrika",
    last_name: "Madgin",
    age: 44,
    visits: 88202,
    progress: 86,
    status: "relationship",
  },
  {
    id: 23,
    first_name: "Jephthah",
    last_name: "Peto",
    age: 53,
    visits: 33548,
    progress: 58,
    status: "relationship",
  },
  {
    id: 24,
    first_name: "Brooks",
    last_name: "Hindrick",
    age: 50,
    visits: 20687,
    progress: 20,
    status: "complicated",
  },
  {
    id: 25,
    first_name: "Welch",
    last_name: "Urridge",
    age: 18,
    visits: 80508,
    progress: 65,
    status: "single",
  },
  {
    id: 26,
    first_name: "Chris",
    last_name: "Aronson",
    age: 56,
    visits: 27604,
    progress: 29,
    status: "complicated",
  },
  {
    id: 27,
    first_name: "Marvin",
    last_name: "Arrigucci",
    age: 56,
    visits: 9743,
    progress: 55,
    status: "single",
  },
  {
    id: 28,
    first_name: "Chris",
    last_name: "O' Liddy",
    age: 23,
    visits: 90416,
    progress: 97,
    status: "single",
  },
  {
    id: 29,
    first_name: "Wallie",
    last_name: "Hassard",
    age: 57,
    visits: 22035,
    progress: 35,
    status: "complicated",
  },
  {
    id: 30,
    first_name: "Bennie",
    last_name: "Timperley",
    age: 44,
    visits: 98825,
    progress: 57,
    status: "single",
  },
  {
    id: 31,
    first_name: "Joe",
    last_name: "Gorton",
    age: 27,
    visits: 47345,
    progress: 28,
    status: "relationship",
  },
  {
    id: 32,
    first_name: "Tomi",
    last_name: "Cullinane",
    age: 32,
    visits: 62507,
    progress: 20,
    status: "relationship",
  },
  {
    id: 33,
    first_name: "Keven",
    last_name: "Hedges",
    age: 61,
    visits: 77321,
    progress: 66,
    status: "complicated",
  },
  {
    id: 34,
    first_name: "Hetti",
    last_name: "Duchateau",
    age: 41,
    visits: 30152,
    progress: 45,
    status: "complicated",
  },
  {
    id: 35,
    first_name: "Wynny",
    last_name: "Hemphall",
    age: 50,
    visits: 35014,
    progress: 99,
    status: "relationship",
  },
  {
    id: 36,
    first_name: "Sydney",
    last_name: "Arrundale",
    age: 33,
    visits: 39676,
    progress: 37,
    status: "complicated",
  },
  {
    id: 37,
    first_name: "Fitzgerald",
    last_name: "Wynne",
    age: 59,
    visits: 64697,
    progress: 50,
    status: "single",
  },
  {
    id: 38,
    first_name: "Max",
    last_name: "Carus",
    age: 30,
    visits: 60497,
    progress: 41,
    status: "relationship",
  },
  {
    id: 39,
    first_name: "Yancey",
    last_name: "Stell",
    age: 26,
    visits: 51127,
    progress: 16,
    status: "relationship",
  },
  {
    id: 40,
    first_name: "Salim",
    last_name: "Burnitt",
    age: 24,
    visits: 63060,
    progress: 5,
    status: "complicated",
  },
  {
    id: 41,
    first_name: "Arabella",
    last_name: "Featherstonhaugh",
    age: 66,
    visits: 50775,
    progress: 1,
    status: "single",
  },
  {
    id: 42,
    first_name: "Cyrus",
    last_name: "Pridmore",
    age: 70,
    visits: 95955,
    progress: 14,
    status: "single",
  },
  {
    id: 43,
    first_name: "Tatum",
    last_name: "Brydie",
    age: 63,
    visits: 52063,
    progress: 67,
    status: "single",
  },
  {
    id: 44,
    first_name: "Gertrud",
    last_name: "Woodgate",
    age: 21,
    visits: 56443,
    progress: 75,
    status: "relationship",
  },
  {
    id: 45,
    first_name: "Antonina",
    last_name: "Joplin",
    age: 60,
    visits: 7025,
    progress: 48,
    status: "single",
  },
  {
    id: 46,
    first_name: "Jaquith",
    last_name: "Redpath",
    age: 60,
    visits: 94355,
    progress: 70,
    status: "complicated",
  },
  {
    id: 47,
    first_name: "Forrester",
    last_name: "Sheryne",
    age: 70,
    visits: 51897,
    progress: 49,
    status: "relationship",
  },
  {
    id: 48,
    first_name: "Cosette",
    last_name: "Ellul",
    age: 57,
    visits: 34611,
    progress: 36,
    status: "single",
  },
  {
    id: 49,
    first_name: "Rollie",
    last_name: "O'Neil",
    age: 44,
    visits: 25866,
    progress: 96,
    status: "single",
  },
  {
    id: 50,
    first_name: "Corey",
    last_name: "Pickavant",
    age: 50,
    visits: 36906,
    progress: 30,
    status: "complicated",
  },
  {
    id: 51,
    first_name: "Judye",
    last_name: "Edginton",
    age: 35,
    visits: 53953,
    progress: 55,
    status: "single",
  },
  {
    id: 52,
    first_name: "Herminia",
    last_name: "Kilgallen",
    age: 33,
    visits: 98304,
    progress: 48,
    status: "single",
  },
  {
    id: 53,
    first_name: "Brigid",
    last_name: "Frowde",
    age: 58,
    visits: 47803,
    progress: 91,
    status: "relationship",
  },
  {
    id: 54,
    first_name: "Britteny",
    last_name: "Kleingrub",
    age: 43,
    visits: 27150,
    progress: 47,
    status: "complicated",
  },
  {
    id: 55,
    first_name: "Debora",
    last_name: "Miranda",
    age: 23,
    visits: 29557,
    progress: 88,
    status: "single",
  },
  {
    id: 56,
    first_name: "Kristoffer",
    last_name: "Ticic",
    age: 56,
    visits: 58813,
    progress: 10,
    status: "complicated",
  },
  {
    id: 57,
    first_name: "Emalee",
    last_name: "Bruneton",
    age: 28,
    visits: 56681,
    progress: 95,
    status: "single",
  },
  {
    id: 58,
    first_name: "Linell",
    last_name: "Pinches",
    age: 57,
    visits: 90369,
    progress: 49,
    status: "single",
  },
  {
    id: 59,
    first_name: "Grove",
    last_name: "Skitt",
    age: 31,
    visits: 40784,
    progress: 79,
    status: "single",
  },
  {
    id: 60,
    first_name: "Klemens",
    last_name: "McVrone",
    age: 24,
    visits: 38813,
    progress: 69,
    status: "complicated",
  },
  {
    id: 61,
    first_name: "Katinka",
    last_name: "Danovich",
    age: 61,
    visits: 16796,
    progress: 79,
    status: "relationship",
  },
  {
    id: 62,
    first_name: "Ernestus",
    last_name: "Tunmore",
    age: 44,
    visits: 38281,
    progress: 29,
    status: "relationship",
  },
  {
    id: 63,
    first_name: "Mauricio",
    last_name: "Coxhell",
    age: 39,
    visits: 69892,
    progress: 9,
    status: "single",
  },
  {
    id: 64,
    first_name: "Angie",
    last_name: "Kleynen",
    age: 40,
    visits: 29862,
    progress: 14,
    status: "single",
  },
  {
    id: 65,
    first_name: "Arvie",
    last_name: "Ruggs",
    age: 41,
    visits: 22612,
    progress: 7,
    status: "relationship",
  },
  {
    id: 66,
    first_name: "Harp",
    last_name: "Stewart",
    age: 59,
    visits: 4803,
    progress: 44,
    status: "complicated",
  },
  {
    id: 67,
    first_name: "Ara",
    last_name: "Begley",
    age: 50,
    visits: 51148,
    progress: 23,
    status: "relationship",
  },
  {
    id: 68,
    first_name: "Joy",
    last_name: "Freathy",
    age: 37,
    visits: 8087,
    progress: 53,
    status: "single",
  },
  {
    id: 69,
    first_name: "Derrik",
    last_name: "Windibank",
    age: 50,
    visits: 50208,
    progress: 35,
    status: "single",
  },
  {
    id: 70,
    first_name: "Shanie",
    last_name: "Tock",
    age: 59,
    visits: 21232,
    progress: 10,
    status: "relationship",
  },
  {
    id: 71,
    first_name: "Byrann",
    last_name: "Jelks",
    age: 44,
    visits: 49943,
    progress: 31,
    status: "complicated",
  },
  {
    id: 72,
    first_name: "Sinclare",
    last_name: "Gheeorghie",
    age: 24,
    visits: 71922,
    progress: 35,
    status: "complicated",
  },
  {
    id: 73,
    first_name: "Nesta",
    last_name: "Peasby",
    age: 50,
    visits: 96113,
    progress: 52,
    status: "complicated",
  },
  {
    id: 74,
    first_name: "Jaquelin",
    last_name: "Waistell",
    age: 38,
    visits: 80023,
    progress: 36,
    status: "single",
  },
  {
    id: 75,
    first_name: "Livia",
    last_name: "Gransden",
    age: 44,
    visits: 72582,
    progress: 34,
    status: "relationship",
  },
  {
    id: 76,
    first_name: "Octavius",
    last_name: "Trayte",
    age: 44,
    visits: 41800,
    progress: 56,
    status: "complicated",
  },
  {
    id: 77,
    first_name: "Wit",
    last_name: "Cosslett",
    age: 45,
    visits: 55904,
    progress: 32,
    status: "single",
  },
  {
    id: 78,
    first_name: "Garvy",
    last_name: "Tammadge",
    age: 41,
    visits: 44967,
    progress: 96,
    status: "complicated",
  },
  {
    id: 79,
    first_name: "Willi",
    last_name: "Coates",
    age: 35,
    visits: 91124,
    progress: 58,
    status: "relationship",
  },
  {
    id: 80,
    first_name: "Stavro",
    last_name: "Leefe",
    age: 55,
    visits: 38241,
    progress: 50,
    status: "complicated",
  },
  {
    id: 81,
    first_name: "Omero",
    last_name: "Gynn",
    age: 58,
    visits: 92955,
    progress: 49,
    status: "relationship",
  },
  {
    id: 82,
    first_name: "Adan",
    last_name: "Beazley",
    age: 42,
    visits: 80834,
    progress: 14,
    status: "complicated",
  },
  {
    id: 83,
    first_name: "Blanche",
    last_name: "Ofener",
    age: 54,
    visits: 59159,
    progress: 98,
    status: "single",
  },
  {
    id: 84,
    first_name: "Derron",
    last_name: "Leathard",
    age: 22,
    visits: 2917,
    progress: 36,
    status: "relationship",
  },
  {
    id: 85,
    first_name: "Harmonie",
    last_name: "Harbard",
    age: 44,
    visits: 25939,
    progress: 85,
    status: "complicated",
  },
  {
    id: 86,
    first_name: "Porty",
    last_name: "Stainbridge",
    age: 42,
    visits: 96053,
    progress: 100,
    status: "relationship",
  },
  {
    id: 87,
    first_name: "Tony",
    last_name: "Gommery",
    age: 64,
    visits: 45598,
    progress: 64,
    status: "complicated",
  },
  {
    id: 88,
    first_name: "Gayla",
    last_name: "Kilroy",
    age: 23,
    visits: 80883,
    progress: 76,
    status: "relationship",
  },
  {
    id: 89,
    first_name: "Cris",
    last_name: "Caser",
    age: 40,
    visits: 12518,
    progress: 95,
    status: "complicated",
  },
  {
    id: 90,
    first_name: "Amity",
    last_name: "Glancey",
    age: 43,
    visits: 10574,
    progress: 88,
    status: "single",
  },
  {
    id: 91,
    first_name: "Harvey",
    last_name: "Giampietro",
    age: 53,
    visits: 81349,
    progress: 71,
    status: "relationship",
  },
  {
    id: 92,
    first_name: "Arlene",
    last_name: "Craddy",
    age: 31,
    visits: 76257,
    progress: 19,
    status: "complicated",
  },
  {
    id: 93,
    first_name: "Amerigo",
    last_name: "Puddle",
    age: 68,
    visits: 91210,
    progress: 74,
    status: "relationship",
  },
  {
    id: 94,
    first_name: "Thibaut",
    last_name: "Yakunchikov",
    age: 50,
    visits: 85072,
    progress: 66,
    status: "single",
  },
  {
    id: 95,
    first_name: "Doy",
    last_name: "Wandtke",
    age: 18,
    visits: 33162,
    progress: 1,
    status: "single",
  },
  {
    id: 96,
    first_name: "Kenny",
    last_name: "Walcot",
    age: 32,
    visits: 17298,
    progress: 14,
    status: "single",
  },
  {
    id: 97,
    first_name: "Yalonda",
    last_name: "Blackesland",
    age: 59,
    visits: 19191,
    progress: 100,
    status: "relationship",
  },
  {
    id: 98,
    first_name: "Torey",
    last_name: "Shrieves",
    age: 51,
    visits: 29685,
    progress: 92,
    status: "single",
  },
  //   {
  //     id: 99,
  //     first_name: "Gerda",
  //     last_name: "Loines",
  //     age: 22,
  //     visits: 65534,
  //     progress: 62,
  //     status: "relationship",
  //   },
  //   {
  //     id: 100,
  //     first_name: "Garald",
  //     last_name: "Stoner",
  //     age: 23,
  //     visits: 62462,
  //     progress: 90,
  //     status: "relationship",
  //   },
];
